first_number = input("Enter first number:")
second_number = input("Enter second number:")
first_number = int(first_number)
second_number = int(second_number)
print("Addition : " + str(first_number + second_number))
print("Subtraction : " + str(first_number - second_number))
print("Division : " + str(first_number / second_number))
print("Multiplication : " + str(first_number * second_number))
print("Exponential : " + str(first_number ** second_number))