first_number = input("Enter first number:")
second_number = input("Enter second number:")
first_number = int(first_number)
second_number = int(second_number)
print(first_number + second_number)
print(first_number - second_number)
print(first_number / second_number)
print(first_number * second_number)
print(first_number ** second_number)